/* soapzpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy.h
   Generated by gSOAP 2.8.91 for /mnt/e/Dev/dev-tools/gsoap/temp/wsdl.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapzpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy_H
#define soapzpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in /mnt/e/Dev/dev-tools/gsoap/temp/wsdl.h, if any
        /// Construct a proxy with new managing context
        zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy();
        /// Copy constructor
        zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy(const zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy();
        /// Initializer used by constructors
        virtual void zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy *copy();
        /// Copy assignment
        zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy& operator=(const zpcu_USCOREtest_USCOREfascia_USCOREdelayWSPortBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'zpcu_test_fascia_delay_Query' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery(_ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery *ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery, _ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQueryResponse &ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQueryResponse) { return this->zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery(NULL, NULL, ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery, ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQueryResponse); }
        /// Web service synchronous operation 'zpcu_test_fascia_delay_Query' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery(const char *soap_endpoint_url, const char *soap_action, _ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery *ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery, _ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQueryResponse &ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQueryResponse) { return this->send_zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery(soap_endpoint_url, soap_action, ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery) || this->recv_zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery(ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQueryResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_zpcu_test_fascia_delay_Query' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery(const char *soap_endpoint_url, const char *soap_action, _ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery *ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery);
        /// Web service asynchronous operation 'recv_zpcu_test_fascia_delay_Query' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQuery(_ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQueryResponse &ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCOREQueryResponse);
        //
        /// Web service synchronous operation 'zpcu_test_fascia_delay_TabularQuery' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery(_ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery *ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery, _ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQueryResponse &ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQueryResponse) { return this->zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery(NULL, NULL, ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery, ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQueryResponse); }
        /// Web service synchronous operation 'zpcu_test_fascia_delay_TabularQuery' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery(const char *soap_endpoint_url, const char *soap_action, _ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery *ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery, _ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQueryResponse &ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQueryResponse) { return this->send_zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery(soap_endpoint_url, soap_action, ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery) || this->recv_zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery(ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQueryResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_zpcu_test_fascia_delay_TabularQuery' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery(const char *soap_endpoint_url, const char *soap_action, _ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery *ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery);
        /// Web service asynchronous operation 'recv_zpcu_test_fascia_delay_TabularQuery' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQuery(_ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQueryResponse &ns1__zpcu_USCOREtest_USCOREfascia_USCOREdelay_USCORETabularQueryResponse);
    };
#endif
