/* soapzpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy.h
   Generated by gSOAP 2.8.116 for /home/fabio/Dev/dev-tools/gsoap/temp/wsdl.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapzpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy_H
#define soapzpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in /home/fabio/Dev/dev-tools/gsoap/temp/wsdl.h, if any
        /// Construct a proxy with new managing context
        zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy();
        /// Copy constructor
        zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy(const zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy();
        /// Initializer used by constructors
        virtual void zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy *copy();
        /// Copy assignment
        zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy& operator=(const zpcu_qinfosedi_fascia_delay_wsWSPortBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'zpcu-qinfosedi-fascia-delay-ws_Query' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int zpcu_qinfosedi_fascia_delay_ws_USCOREQuery(_ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQuery *ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQuery, _ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQueryResponse &ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQueryResponse) { return this->zpcu_qinfosedi_fascia_delay_ws_USCOREQuery(NULL, NULL, ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQuery, ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQueryResponse); }
        /// Web service synchronous operation 'zpcu-qinfosedi-fascia-delay-ws_Query' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int zpcu_qinfosedi_fascia_delay_ws_USCOREQuery(const char *soap_endpoint_url, const char *soap_action, _ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQuery *ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQuery, _ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQueryResponse &ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQueryResponse) { return this->send_zpcu_qinfosedi_fascia_delay_ws_USCOREQuery(soap_endpoint_url, soap_action, ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQuery) || this->recv_zpcu_qinfosedi_fascia_delay_ws_USCOREQuery(ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQueryResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_zpcu-qinfosedi-fascia-delay-ws_Query' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_zpcu_qinfosedi_fascia_delay_ws_USCOREQuery(const char *soap_endpoint_url, const char *soap_action, _ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQuery *ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQuery);
        /// Web service asynchronous operation 'recv_zpcu-qinfosedi-fascia-delay-ws_Query' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_zpcu_qinfosedi_fascia_delay_ws_USCOREQuery(_ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQueryResponse &ns1__zpcu_qinfosedi_fascia_delay_ws_USCOREQueryResponse);
        //
        /// Web service synchronous operation 'zpcu-qinfosedi-fascia-delay-ws_TabularQuery' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery(_ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery *ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery, _ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQueryResponse &ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQueryResponse) { return this->zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery(NULL, NULL, ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery, ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQueryResponse); }
        /// Web service synchronous operation 'zpcu-qinfosedi-fascia-delay-ws_TabularQuery' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery(const char *soap_endpoint_url, const char *soap_action, _ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery *ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery, _ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQueryResponse &ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQueryResponse) { return this->send_zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery(soap_endpoint_url, soap_action, ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery) || this->recv_zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery(ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQueryResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_zpcu-qinfosedi-fascia-delay-ws_TabularQuery' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery(const char *soap_endpoint_url, const char *soap_action, _ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery *ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery);
        /// Web service asynchronous operation 'recv_zpcu-qinfosedi-fascia-delay-ws_TabularQuery' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_zpcu_qinfosedi_fascia_delay_ws_USCORETabularQuery(_ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQueryResponse &ns1__zpcu_qinfosedi_fascia_delay_ws_USCORETabularQueryResponse);
    };
#endif
